# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-25 11:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0002_auto_20160919_1539'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u59d3\u540d')),
            ],
        ),
        migrations.CreateModel(
            name='MM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, verbose_name='\u59d3\u540d')),
            ],
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mm',
            name='info',
            field=models.ManyToManyField(to='user_admin.BasicInfo', verbose_name='jjyy'),
        ),
        migrations.AddField(
            model_name='fore',
            name='info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_admin.BasicInfo', verbose_name='jjyy'),
        ),
    ]
