# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 09:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0004_auto_20161013_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'permissions': (('read', 'Atleaset read the records'),)},
        ),
    ]
