# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-13 09:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0005_auto_20161013_1734'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'permissions': (('read_basicinfo', 'At leaset read the records'),)},
        ),
    ]
