# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-23 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0007_employeeinfo_month_salaryrecords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeinfo',
            name='salary_level',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='\u5de5\u8d44'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='allowance',
            field=models.FloatField(blank=True, null=True, verbose_name='\u8865\u8d34'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='base_salary',
            field=models.FloatField(blank=True, null=True, verbose_name='\u57fa\u672c\u5de5\u8d44'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='merit_pay',
            field=models.FloatField(blank=True, null=True, verbose_name='\u7ee9\u6548\u5de5\u8d44'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='reserved_funds',
            field=models.FloatField(blank=True, null=True, verbose_name='\u793e\u4fdd'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='social_security',
            field=models.FloatField(blank=True, null=True, verbose_name='\u793e\u4fdd'),
        ),
    ]
