# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-03 07:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('user_admin', '0009_auto_20161031_1652'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(default='', max_length=200, verbose_name='model')),
                ('permit', models.TextField(default='', verbose_name='permit')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='group')),
            ],
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='adapt_day',
            field=models.FloatField(blank=True, null=True, verbose_name='\u4fee\u6b63\u5929\u6570'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='reserved_funds',
            field=models.FloatField(blank=True, null=True, verbose_name='\u516c\u79ef\u91d1'),
        ),
    ]
