# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 01:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0011_auto_20161104_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permitmodel',
            name='group',
        ),
        migrations.DeleteModel(
            name='PermitModel',
        ),
    ]
