# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 09:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0012_auto_20161114_0917'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeinfo',
            options={'verbose_name': '\u5458\u5de5\u4fe1\u606f'},
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
