# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 09:46
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_admin', '0013_auto_20161218_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employ_id', models.CharField(blank=True, max_length=50, verbose_name='\u804c\u5458ID')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='\u804c\u4f4d')),
                ('salary_level', models.FloatField(blank=True, max_length=100, null=True, verbose_name='\u5de5\u8d44')),
            ],
            options={
                'verbose_name': '\u5de5\u4f5c\u4fe1\u606f',
            },
        ),
        migrations.RemoveField(
            model_name='employeeinfo',
            name='baseinfo',
        ),
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'permissions': (('read_basicinfo', 'At leaset read the records'),), 'verbose_name': '\u57fa\u672c\u4fe1\u606f'},
        ),
        migrations.AlterModelOptions(
            name='salaryrecords',
            options={'verbose_name': '\u5de5\u8d44\u8bb0\u5f55'},
        ),
        migrations.RemoveField(
            model_name='basicinfo',
            name='user',
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='empoyee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.EmployeeModel', verbose_name='\u5458\u5de5'),
        ),
        migrations.DeleteModel(
            name='EmployeeInfo',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='baseinfo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_admin.BasicInfo', verbose_name='\u57fa\u672c\u4fe1\u606f'),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
