# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 02:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0016_basicinfo_head'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeemodel',
            options={'verbose_name': 'Employee Info'},
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='age',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u5e74\u9f84'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='head',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='name',
            field=models.CharField(blank=True, max_length=50, verbose_name='\u540d\u5b57'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='employ_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u5458\u5de5ID'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='salary_level',
            field=models.FloatField(blank=True, max_length=100, null=True, verbose_name='\u5de5\u8d44\u7ea7\u522b'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u8d26\u53f7'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='empoyee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.EmployeeModel', verbose_name='employee'),
        ),
        migrations.AlterField(
            model_name='salaryrecords',
            name='month',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='\u6708\u4efd'),
            preserve_default=False,
        ),
    ]
