# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-03-06 02:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0017_auto_20170306_1009'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaryrecords',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='\u786e\u8ba4\u8fc7'),
        ),
    ]
