# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-19 09:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0020_auto_20170319_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='label',
            field=models.CharField(blank=True, max_length=300, verbose_name='department label'),
        ),
    ]
