# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-06-03 08:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_admin', '0022_auto_20170410_2208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basicinfo',
            options={'verbose_name': '\u57fa\u672c\u4fe1\u606f'},
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='employ_id',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='eid',
            field=models.CharField(default='', max_length=30, verbose_name='employee id'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='gen',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('femal', 'femal')], max_length=30, verbose_name='gen'),
        ),
        migrations.AlterField(
            model_name='basicinfo',
            name='head',
            field=models.CharField(blank=True, default='/static/image/user.jpg', max_length=200, verbose_name='\u5934\u50cf'),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='account'),
        ),
    ]
