# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 12:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('workload', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workmodel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_works', to=settings.AUTH_USER_MODEL, verbose_name='\u7ba1\u7406\u8005'),
        ),
    ]
