# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0002_workmodel_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskmodel',
            name='desp',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u4ecb\u7ecd'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='long_desp',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u4ecb\u7ecd'),
        ),
        migrations.AddField(
            model_name='workmodel',
            name='short_desp',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5de5\u4f5c\u7b80\u4ecb'),
        ),
    ]
