# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-29 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workload', '0003_auto_20161218_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskmodel',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.EmployeeModel', verbose_name='\u4ece\u5c5e\u4e8e'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managed_works', to='user_admin.EmployeeModel', verbose_name='\u7ba1\u7406\u8005'),
        ),
        migrations.AlterField(
            model_name='workmodel',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_admin.EmployeeModel', verbose_name='worker'),
        ),
    ]
