# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-18 09:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('director', '0002_auto_20161114_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logmodel',
            name='detail',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6'),
        ),
        migrations.AlterField(
            model_name='logmodel',
            name='kind',
            field=models.CharField(blank=True, max_length=100, verbose_name='\u7c7b\u522b'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group', verbose_name='\u7528\u6237\u7ec4'),
        ),
        migrations.AlterField(
            model_name='permitmodel',
            name='permit',
            field=models.TextField(default='{}', verbose_name='\u7528\u6237\u6743\u9650'),
        ),
    ]
