# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-06 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=200, verbose_name='key')),
                ('op', models.CharField(max_length=100, verbose_name='\u64cd\u4f5c\u7c7b\u578b')),
                ('detail', models.TextField(blank=True, verbose_name='\u7ec6\u8282')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u64cd\u4f5c\u8005')),
            ],
        ),
    ]
